/* 菜谱数据与分类定义。被 app.js 使用，需在 app.js 之前加载。 */
const BUILTIN = [
  {cat:'burger',sub:'经典款',flag:'🇺🇸',name:'美式芝士汉堡',en:'Cheeseburger',p:['beef'],ing:'牛肉饼、切达芝士、生菜、番茄、洋葱、酸黄瓜、汉堡胚、番茄酱'},
  {cat:'burger',sub:'经典款',flag:'🇺🇸',name:'炸鸡堡',en:'Fried Chicken Burger',p:['chicken'],ing:'炸鸡排、卷心菜丝、蛋黄酱、酸黄瓜、汉堡胚'},
  {cat:'burger',sub:'经典款',flag:'🌍',name:'鱼排堡',en:'Fish Burger',p:['sea'],ing:'炸白身鱼排、塔塔酱、芝士片、生菜、汉堡胚'},
  {cat:'burger',sub:'经典款',flag:'🌱',name:'素食堡',en:'Veggie Burger',p:['tofu'],ing:'黑豆或植物肉饼、生菜、番茄、洋葱圈、芝士、汉堡胚'},
  {cat:'burger',sub:'异国特色',flag:'🇯🇵',name:'照烧猪肉堡',en:'Teriyaki Pork Burger',p:['pork'],ing:'猪肉片、照烧汁、生菜、芝士、蛋黄酱、汉堡胚'},
  {cat:'burger',sub:'异国特色',flag:'🇯🇵',name:'日式米汉堡',en:'Rice Burger',p:['beef','sea'],ing:'压实米饭饼（代替面包）、烤肉或虾、生菜、照烧或海鲜酱'},
  {cat:'burger',sub:'异国特色',flag:'🇹🇷',name:'土耳其湿汉堡',en:'Islak Burger',p:['beef'],ing:'超薄牛肉饼、蒜、黑胡椒、浸番茄蒜酱的软面包'},
  {cat:'burger',sub:'异国特色',flag:'🇦🇺',name:'澳式甜菜根汉堡',en:'Aussie Burger',p:['beef','egg'],ing:'牛肉饼、甜菜根、菠萝片、煎蛋、培根、生菜、番茄'},
  {cat:'burger',sub:'异国特色',flag:'🇲🇾',name:'马来蛋包汉堡',en:'Ramly Burger',p:['beef','chicken','egg'],ing:'牛肉或鸡肉饼裹蛋皮、卷心菜丝、蛋黄酱、黄瓜、伍斯特酱、辣酱'},
  {cat:'burger',sub:'异国特色',flag:'🇮🇳',name:'印度炸土豆堡',en:'Vada Pav',p:['tofu'],ing:'炸土豆饼、面包、蒜辣酱、青辣酱、绿辣椒'},

  {cat:'sandwich',sub:'冷三明治',flag:'🇺🇸',name:'俱乐部三明治',en:'Club Sandwich',p:['chicken','egg'],ing:'三层吐司、火鸡或鸡肉、培根、生菜、番茄、煎蛋、蛋黄酱'},
  {cat:'sandwich',sub:'冷三明治',flag:'🇺🇸',name:'培根生菜番茄三明治',en:'BLT',p:['pork'],ing:'培根、生菜、番茄、蛋黄酱、烤吐司'},
  {cat:'sandwich',sub:'冷三明治',flag:'🇯🇵',name:'鸡蛋三明治',en:'Tamago Sando',p:['egg'],ing:'鸡蛋沙拉、蛋黄酱、白吐司、盐、糖'},
  {cat:'sandwich',sub:'冷三明治',flag:'🌍',name:'金枪鱼三明治',en:'Tuna Sando',p:['sea'],ing:'金枪鱼、蛋黄酱、洋葱碎、玉米粒、吐司'},
  {cat:'sandwich',sub:'热压三明治',flag:'🇮🇹',name:'意式帕尼尼',en:'Panini',p:['pork'],ing:'恰巴塔面包、火腿或萨拉米、马苏里拉、番茄、罗勒（压烤）'},
  {cat:'sandwich',sub:'热压三明治',flag:'🇨🇺',name:'古巴三明治',en:'Cuban Sandwich',p:['pork'],ing:'烤猪肉、火腿、瑞士芝士、酸黄瓜、黄芥末、古巴面包（压烤）'},
  {cat:'sandwich',sub:'热压三明治',flag:'🇫🇷',name:'法式火腿芝士热三明治',en:'Croque Monsieur',p:['pork','egg'],ing:'火腿、格鲁耶尔芝士、白酱、烤吐司（加煎蛋即 Madame）'},
  {cat:'sandwich',sub:'热压三明治',flag:'🇯🇵',name:'炸猪排三明治',en:'Katsu Sando',p:['pork'],ing:'炸猪排、卷心菜丝、猪排酱、黄芥末、白吐司'},
  {cat:'sandwich',sub:'长面包·潜艇',flag:'🇺🇸',name:'潜艇堡',en:'Sub / Hoagie',p:['pork','chicken'],ing:'长面包、冷切肉、芝士、生菜、番茄、洋葱、油醋汁'},
  {cat:'sandwich',sub:'长面包·潜艇',flag:'🇺🇸',name:'费城芝士牛肉',en:'Philly Cheesesteak',p:['beef'],ing:'薄牛肉片、洋葱、融化芝士、长面包'},
  {cat:'sandwich',sub:'长面包·潜艇',flag:'🇻🇳',name:'越南法包',en:'Bánh Mì',p:['pork'],ing:'法棍、烤猪肉、腌萝卜胡萝卜、黄瓜、香菜、辣椒、蛋黄酱'},
  {cat:'sandwich',sub:'长面包·潜艇',flag:'🇲🇽',name:'墨西哥托塔',en:'Torta',p:['pork','chicken'],ing:'telera 软面包、烤肉、牛油果、豆泥、辣椒、芝士、番茄'},

  {cat:'wrap',sub:'美洲卷',flag:'🇲🇽',name:'墨西哥卷饼',en:'Burrito',p:['beef','chicken','tofu'],ing:'面粉薄饼、米饭、豆子、肉、芝士、莎莎、酸奶油、牛油果'},
  {cat:'wrap',sub:'美洲卷',flag:'🇲🇽',name:'塔可',en:'Taco',p:['beef','pork'],ing:'玉米饼、烤肉、洋葱、香菜、莎莎、青柠'},
  {cat:'wrap',sub:'美洲卷',flag:'🇺🇸',name:'鸡肉卷',en:'Chicken Wrap',p:['chicken'],ing:'薄饼、香煎鸡肉、生菜、番茄、芝士、酸奶酱'},
  {cat:'wrap',sub:'中东·旋转烤肉卷',flag:'🇱🇧',name:'黎巴嫩沙威玛',en:'Shawarma',p:['chicken','beef'],ing:'转烤腌肉、皮塔或 lavash、蒜酱、腌菜、芝麻酱'},
  {cat:'wrap',sub:'中东·旋转烤肉卷',flag:'🇬🇷',name:'希腊旋转烤肉卷',en:'Gyros',p:['pork','chicken'],ing:'转烤猪或鸡肉、皮塔、酸奶黄瓜酱、薯条、番茄、洋葱'},
  {cat:'wrap',sub:'中东·旋转烤肉卷',flag:'🇹🇷',name:'土耳其旋转烤肉',en:'Döner Kebab',p:['beef'],ing:'转烤腌肉、lavash 或 pita、洋葱、番茄、酸奶酱'},
  {cat:'wrap',sub:'中东·旋转烤肉卷',flag:'🌍',name:'中东鹰嘴豆丸卷',en:'Falafel Wrap',p:['tofu'],ing:'炸鹰嘴豆丸、皮塔、生菜、番茄、酸黄瓜、芝麻酱'},
  {cat:'wrap',sub:'亚洲卷',flag:'🇨🇳',name:'手抓饼卷',en:'Scallion Pancake Wrap',p:['egg','pork'],ing:'手抓饼、煎蛋、炒肉、生菜、甜面酱'},
  {cat:'wrap',sub:'亚洲卷',flag:'🇮🇳',name:'印度卡蒂卷',en:'Kathi Roll',p:['chicken','egg'],ing:'帕拉塔饼、烤腌肉、洋葱、青柠、酸辣酱'},
  {cat:'wrap',sub:'亚洲卷',flag:'🇻🇳',name:'越南夏卷',en:'Summer Roll',p:['pork','sea'],ing:'米纸、虾或猪肉、米粉、生菜、薄荷、香菜、花生蘸酱（不炸）'},
  {cat:'wrap',sub:'亚洲卷',flag:'🇵🇭',name:'菲律宾春卷',en:'Lumpia',p:['pork','sea'],ing:'薄春卷皮、猪肉或虾、胡萝卜、卷心菜、豆芽（炸）'},

  {cat:'rice',sub:'炒饭',flag:'🇨🇳',name:'扬州炒饭',en:'Yangzhou Fried Rice',p:['egg','sea'],ing:'米饭、鸡蛋、虾仁、叉烧、青豆、胡萝卜、葱'},
  {cat:'rice',sub:'炒饭',flag:'🇮🇩',name:'印尼炒饭',en:'Nasi Goreng',p:['chicken','egg'],ing:'米饭、甜酱油、虾酱、葱蒜辣椒、煎蛋、虾片'},
  {cat:'rice',sub:'炒饭',flag:'🇹🇭',name:'泰式菠萝炒饭',en:'Pineapple Fried Rice',p:['sea','egg'],ing:'米饭、虾、菠萝、腰果、咖喱粉、葱、鸡蛋'},
  {cat:'rice',sub:'炒饭',flag:'🇰🇷',name:'韩式泡菜炒饭',en:'Kimchi Fried Rice',p:['pork','egg'],ing:'米饭、泡菜、猪肉、麻油、煎蛋、海苔'},
  {cat:'rice',sub:'盖饭·丼',flag:'🇯🇵',name:'日式牛肉饭',en:'Gyudon',p:['beef'],ing:'肥牛片、洋葱、酱油味醂糖、米饭、温泉蛋'},
  {cat:'rice',sub:'盖饭·丼',flag:'🇯🇵',name:'照烧鸡腿饭',en:'Teriyaki Chicken Don',p:['chicken'],ing:'鸡腿、照烧汁、米饭、白芝麻、葱'},
  {cat:'rice',sub:'盖饭·丼',flag:'🇯🇵',name:'亲子丼',en:'Oyakodon',p:['chicken','egg'],ing:'鸡肉、鸡蛋、洋葱、高汤酱汁、米饭、葱'},
  {cat:'rice',sub:'盖饭·丼',flag:'🇯🇵',name:'天妇罗盖饭',en:'Tendon',p:['sea'],ing:'米饭、炸虾天妇罗、蔬菜天妇罗、天丼酱汁'},
  {cat:'rice',sub:'盖饭·丼',flag:'🇯🇵',name:'日式咖喱饭',en:'Curry Rice',p:['chicken','beef','pork'],ing:'肉、土豆、胡萝卜、洋葱、咖喱块、米饭'},
  {cat:'rice',sub:'盖饭·丼',flag:'🇹🇼',name:'台式卤肉饭',en:'Lu Rou Fan',p:['pork','egg'],ing:'卤肉丁、红葱酥、酱油、冰糖、五香粉、米饭、卤蛋'},
  {cat:'rice',sub:'盖饭·丼',flag:'🇺🇸',name:'夏威夷生鱼饭',en:'Poke Bowl',p:['sea'],ing:'米饭、生三文鱼或金枪鱼、酱油、牛油果、海藻、洋葱、芝麻'},
  {cat:'rice',sub:'拌饭',flag:'🇰🇷',name:'韩式石锅拌饭',en:'Bibimbap',p:['beef','egg'],ing:'米饭、牛肉末、菠菜、豆芽、胡萝卜、煎蛋、辣椒酱、麻油'},
  {cat:'rice',sub:'拌饭',flag:'🇯🇵',name:'鸡蛋拌饭',en:'Tamago Kake Gohan',p:['egg'],ing:'热米饭、生鸡蛋、酱油、葱'},
  {cat:'rice',sub:'煲仔·焖饭',flag:'🇨🇳',name:'广式煲仔饭',en:'Claypot Rice',p:['pork','chicken'],ing:'米饭、腊肠、腊肉或鸡、青菜、酱油、葱（瓦煲焦底）'},
  {cat:'rice',sub:'煲仔·焖饭',flag:'🇸🇬',name:'海南鸡饭',en:'Hainanese Chicken Rice',p:['chicken'],ing:'鸡腿、姜葱、鸡油香米饭、蒜姜蓉酱、黄瓜'},
  {cat:'rice',sub:'手抓饭·香饭',flag:'🇮🇳',name:'印度比尔亚尼',en:'Biryani',p:['chicken','beef'],ing:'巴斯马蒂香米、腌肉、藏红花、洋葱酥、豆蔻丁香、酸奶'},
  {cat:'rice',sub:'手抓饭·香饭',flag:'🇲🇾',name:'马来椰浆饭',en:'Nasi Lemak',p:['sea','egg'],ing:'椰浆饭、江鱼仔、花生、黄瓜、参巴辣酱、水煮蛋'},
  {cat:'rice',sub:'饭团·饭卷',flag:'🇯🇵',name:'日式饭团',en:'Onigiri',p:['sea','egg'],ing:'米饭、三文鱼或梅子或肉松、海苔、盐'},
  {cat:'rice',sub:'饭团·饭卷',flag:'🇰🇷',name:'韩式紫菜包饭',en:'Kimbap',p:['beef','egg'],ing:'海苔、米饭、牛肉或火腿、黄瓜、胡萝卜、腌萝卜、蛋皮、麻油'},
  {cat:'rice',sub:'饭团·饭卷',flag:'🇯🇵',name:'寿司卷',en:'Sushi Maki',p:['sea'],ing:'醋饭、海苔、三文鱼或金枪鱼或黄瓜、牛油果'},
  {cat:'rice',sub:'饭团·饭卷',flag:'🇹🇼',name:'台式饭团',en:'Fan Tuan',p:['pork'],ing:'糯米饭、肉松、卤肉、萝卜干、油条'},
  {cat:'rice',sub:'饭团·饭卷',flag:'🇮🇹',name:'意式炸饭团',en:'Arancini',p:['beef'],ing:'米饭、马苏里拉、肉酱、面包糠（炸）'},

  {cat:'noodle',sub:'汤面',flag:'🇯🇵',name:'日式拉面',en:'Ramen',p:['pork','egg'],ing:'拉面、豚骨或酱油汤、叉烧、溏心蛋、海苔、葱'},
  {cat:'noodle',sub:'汤面',flag:'🇻🇳',name:'越南牛肉粉',en:'Phở',p:['beef'],ing:'河粉、牛骨汤、生熟牛肉、八角桂皮、豆芽、香菜、青柠'},
  {cat:'noodle',sub:'汤面',flag:'🇹🇭',name:'泰北咖喱面',en:'Khao Soi',p:['chicken'],ing:'蛋面、椰浆红咖喱汤、鸡肉、酸菜、红葱、青柠'},
  {cat:'noodle',sub:'汤面',flag:'🇨🇳',name:'兰州牛肉拉面',en:'Lanzhou Beef Noodles',p:['beef'],ing:'手拉面、清牛肉汤、牛肉片、白萝卜、辣椒油、香菜'},
  {cat:'noodle',sub:'汤面',flag:'🇲🇾',name:'马来叻沙',en:'Laksa',p:['sea','chicken'],ing:'米粉、椰浆或酸辣汤、虾、鱼饼、豆芽、叻沙叶'},
  {cat:'noodle',sub:'拌面·炒面',flag:'🇹🇭',name:'泰式炒河粉',en:'Pad Thai',p:['sea','egg'],ing:'河粉、虾、豆腐、鸡蛋、豆芽、罗望子鱼露汁、花生碎'},
  {cat:'noodle',sub:'拌面·炒面',flag:'🇨🇳',name:'中式炒面',en:'Chow Mein / Lo Mein',p:['chicken','pork'],ing:'蛋面、肉丝、卷心菜、胡萝卜、蚝油、酱油'},
  {cat:'noodle',sub:'拌面·炒面',flag:'🇰🇷',name:'韩式杂菜',en:'Japchae',p:['beef','egg'],ing:'红薯粉丝、牛肉、菠菜、胡萝卜、香菇、麻油、酱油'},
  {cat:'noodle',sub:'拌面·炒面',flag:'🇨🇳',name:'担担面',en:'Dan Dan Noodles',p:['pork'],ing:'面条、芝麻酱、辣椒油、肉末、花生、葱'},
  {cat:'noodle',sub:'拌面·炒面',flag:'🇸🇬',name:'新加坡炒粿条',en:'Char Kway Teow',p:['sea','egg'],ing:'宽河粉、虾、腊肠、豆芽、鸡蛋、酱油'},

  {cat:'congee',sub:'粥',flag:'🇨🇳',name:'皮蛋瘦肉粥',en:'Century Egg Congee',p:['pork','egg'],ing:'大米、皮蛋、瘦肉、姜丝、葱、白胡椒'},
  {cat:'congee',sub:'粥',flag:'🇨🇳',name:'潮汕海鲜粥',en:'Seafood Congee',p:['sea'],ing:'米、虾、鱿鱼、蛤蜊、芹菜、葱、姜'},
  {cat:'congee',sub:'粥',flag:'🇹🇭',name:'泰式鸡肉粥',en:'Jok',p:['chicken'],ing:'米、鸡肉、姜、鱼露、葱、油条'},
  {cat:'congee',sub:'汤饭·泡饭',flag:'🇯🇵',name:'日式茶泡饭',en:'Ochazuke',p:['sea'],ing:'米饭、绿茶或高汤、鲑鱼或梅子、海苔、芥末'},
  {cat:'congee',sub:'汤饭·泡饭',flag:'🇰🇷',name:'韩式牛肉汤饭',en:'Gukbap',p:['beef'],ing:'米饭、牛肉、萝卜、葱、蒜、牛骨汤'},
  {cat:'congee',sub:'汤饭·泡饭',flag:'🇰🇷',name:'泡菜豆腐汤配饭',en:'Kimchi Jjigae + Rice',p:['pork','tofu'],ing:'泡菜、豆腐、猪肉、辣椒粉、葱、米饭'},

  {cat:'bundump',sub:'蒸包·夹饼',flag:'🇹🇼',name:'台式刈包',en:'Gua Bao',p:['pork'],ing:'蒸饼、卤肉、酸菜、花生粉、香菜'},
  {cat:'bundump',sub:'蒸包·夹饼',flag:'🇨🇳',name:'肉夹馍',en:'Rou Jia Mo',p:['pork'],ing:'白吉馍、卤肉碎、青椒、香菜'},
  {cat:'bundump',sub:'蒸包·夹饼',flag:'🇨🇳',name:'叉烧包',en:'Char Siu Bao',p:['pork'],ing:'发面、叉烧肉、蚝油酱汁、糖'},
  {cat:'bundump',sub:'蒸包·夹饼',flag:'🇻🇪',name:'委内瑞拉玉米饼',en:'Arepa',p:['chicken','tofu'],ing:'玉米饼对半、鸡肉丝或黑豆、芝士、牛油果'},
  {cat:'bundump',sub:'蒸包·夹饼',flag:'🌎',name:'拉美肉馅饼',en:'Empanada',p:['beef','chicken'],ing:'面皮、碎肉、洋葱、水煮蛋、橄榄、孜然（烤或炸）'},
  {cat:'bundump',sub:'饺子',flag:'🇨🇳',name:'中式饺子',en:'Jiaozi',p:['pork'],ing:'饺子皮、猪肉、白菜、韭菜、姜、葱（煮/蒸/煎）'},
  {cat:'bundump',sub:'饺子',flag:'🇨🇳',name:'上海小笼包',en:'Xiaolongbao',p:['pork'],ing:'薄面皮、猪肉、皮冻（汤汁）、姜、醋蘸料'},
  {cat:'bundump',sub:'饺子',flag:'🇯🇵',name:'日式煎饺',en:'Gyoza',p:['pork'],ing:'饺子皮、猪肉、卷心菜、韭菜、蒜姜（煎+蒸）'},
  {cat:'bundump',sub:'饺子',flag:'🇰🇷',name:'韩式饺子',en:'Mandu',p:['pork','tofu'],ing:'饺子皮、猪肉、豆腐、泡菜、粉丝、葱'},
  {cat:'bundump',sub:'饺子',flag:'🇨🇳',name:'馄饨',en:'Wonton',p:['pork','sea'],ing:'薄馄饨皮、猪肉或虾、葱、高汤'},
  {cat:'bundump',sub:'饺子',flag:'🇳🇵',name:'尼泊尔蒸饺',en:'Momo',p:['chicken'],ing:'面皮、鸡肉或蔬菜、洋葱、姜蒜、番茄蘸酱'},
  {cat:'bundump',sub:'蒸炸点心',flag:'🇨🇳',name:'虾饺',en:'Har Gow',p:['sea'],ing:'澄面皮、虾仁、竹笋、猪油'},
  {cat:'bundump',sub:'蒸炸点心',flag:'🇨🇳',name:'烧卖',en:'Siu Mai',p:['pork','sea'],ing:'黄色薄皮、猪肉、虾、香菇'},
  {cat:'bundump',sub:'蒸炸点心',flag:'🇨🇳',name:'春卷',en:'Spring Roll',p:['pork','sea'],ing:'春卷皮、肉丝或虾、卷心菜、胡萝卜、豆芽（炸）'},

  {cat:'snack',sub:'烧烤串',flag:'🇯🇵',name:'日式烤鸡串',en:'Yakitori',p:['chicken'],ing:'鸡肉块、葱、照烧汁或盐、竹签'},
  {cat:'snack',sub:'烧烤串',flag:'🌏',name:'东南亚沙嗲',en:'Satay',p:['chicken','beef'],ing:'腌肉串、姜黄香茅、花生蘸酱、黄瓜洋葱'},
  {cat:'snack',sub:'烧烤串',flag:'🌍',name:'中东烤肉串',en:'Shish Kebab',p:['beef'],ing:'腌牛肉块、洋葱、彩椒、孜然、竹签'},
  {cat:'snack',sub:'烧烤串',flag:'🇯🇵',name:'日式烤鱿鱼',en:'Ikayaki',p:['sea'],ing:'鱿鱼、酱油糖照烧汁、竹签'},
  {cat:'snack',sub:'油炸·煎烙小吃',flag:'🇯🇵',name:'大阪章鱼烧',en:'Takoyaki',p:['sea','egg'],ing:'面糊、章鱼丁、红姜、葱、章鱼烧酱、蛋黄酱、木鱼花'},
  {cat:'snack',sub:'油炸·煎烙小吃',flag:'🇯🇵',name:'大阪烧',en:'Okonomiyaki',p:['pork','egg'],ing:'卷心菜、面糊、鸡蛋、猪肉片、大阪烧酱、蛋黄酱、木鱼花'},
  {cat:'snack',sub:'油炸·煎烙小吃',flag:'🇯🇵',name:'日式可乐饼',en:'Korokke',p:['tofu'],ing:'土豆泥、洋葱、面包糠（可加肉末，炸）'},
  {cat:'snack',sub:'油炸·煎烙小吃',flag:'🇨🇳',name:'葱油饼',en:'Scallion Pancake',p:['tofu'],ing:'面团、葱、盐、油（煎）'},

  {cat:'dessert',sub:'米食甜点',flag:'🇹🇭',name:'泰式芒果糯米饭',en:'Mango Sticky Rice',p:['tofu'],ing:'糯米、椰浆、糖、盐、芒果'},
  {cat:'dessert',sub:'米食甜点',flag:'🇨🇳',name:'汤圆',en:'Tang Yuan',p:['tofu'],ing:'糯米粉、黑芝麻或花生馅、糖、姜糖水'},
  {cat:'dessert',sub:'米食甜点',flag:'🇯🇵',name:'日式麻糬',en:'Mochi',p:['tofu'],ing:'糯米粉、红豆沙或草莓或冰淇淋'},
  {cat:'dessert',sub:'冰品',flag:'🇰🇷',name:'韩式刨冰',en:'Bingsu',p:['tofu'],ing:'刨冰、炼乳、红豆、水果、年糕'},
  {cat:'dessert',sub:'冰品',flag:'🇵🇭',name:'菲律宾刨冰',en:'Halo-Halo',p:['egg'],ing:'刨冰、炼乳、豆、果冻、布丁、紫薯冰淇淋'},
  {cat:'dessert',sub:'冰品',flag:'🇻🇳',name:'越南甜汤',en:'Chè',p:['tofu'],ing:'绿豆或红豆、椰浆、西米、果冻'},
  {cat:'dessert',sub:'糕饼',flag:'🇰🇷',name:'韩式糖饼',en:'Hotteok',p:['tofu'],ing:'面团、红糖、坚果、肉桂（煎）'},
  {cat:'dessert',sub:'糕饼',flag:'🇯🇵',name:'鲷鱼烧',en:'Taiyaki',p:['egg'],ing:'面糊、红豆沙或卡仕达（鱼形模具）'},
  {cat:'dessert',sub:'糕饼',flag:'🇨🇳',name:'蛋挞',en:'Egg Tart',p:['egg'],ing:'酥皮、鸡蛋、牛奶、糖'},
  {cat:'dessert',sub:'糕饼',flag:'🇯🇵',name:'铜锣烧',en:'Dorayaki',p:['egg'],ing:'松饼皮、红豆沙'},
];

const formats = {
  custom:{em:'⭐',name:'我的菜谱',desc:'你用 AI 一句话生成、云端同步的菜。'},
  burger:{em:'🍔',name:'汉堡',desc:'肉饼夹圆面包，全球都有本地版本。'},
  sandwich:{em:'🥪',name:'三明治',desc:'面包夹料，分冷食、热压、长面包潜艇。'},
  wrap:{em:'🌯',name:'卷类',desc:'薄饼或皮塔卷馅，美洲、中东、亚洲各有风格。'},
  rice:{em:'🍚',name:'饭类',desc:'亚洲餐桌的核心：炒、盖、拌、煲、抓、团。'},
  noodle:{em:'🍜',name:'面·粉',desc:'汤的、拌的、炒的，米麦皆有。'},
  congee:{em:'🥘',name:'粥·汤饭',desc:'熬煮或汤泡的米食，暖胃好消化。'},
  bundump:{em:'🥟',name:'包·饺·点心',desc:'面皮包馅：蒸包夹饼、饺子、蒸炸点心。'},
  snack:{em:'🍢',name:'串·小吃',desc:'街边手持：烤串、油炸、铁板煎烙。'},
  dessert:{em:'🍰',name:'甜品',desc:'亚洲甜点：米食、冰品、糕饼。'},
};
const formatOrder=['custom','burger','sandwich','wrap','rice','noodle','congee','bundump','snack','dessert'];
const pInfo={pork:'🐷猪',chicken:'🐔鸡',beef:'🐄牛',sea:'🐟鱼虾',egg:'🥚蛋',tofu:'🫛豆腐素'};
const PSET=['pork','chicken','beef','sea','egg','tofu'];
