/* 菜谱数据与分类定义。被 app.js 使用，需在 app.js 之前加载。 */
const BUILTIN = [
  {cat:'burger',sub:'经典款',sub_en:'Classic',flag:'🇺🇸',name:'美式芝士汉堡',en:'Cheeseburger',p:['beef'],ing:'牛肉饼、切达芝士、生菜、番茄、洋葱、酸黄瓜、汉堡胚、番茄酱',ing_en:'Beef patty, cheddar, lettuce, tomato, onion, pickles, bun, ketchup'},
  {cat:'burger',sub:'经典款',sub_en:'Classic',flag:'🇺🇸',name:'炸鸡堡',en:'Fried Chicken Burger',p:['chicken'],ing:'炸鸡排、卷心菜丝、蛋黄酱、酸黄瓜、汉堡胚',ing_en:'Fried chicken fillet, shredded cabbage, mayo, pickles, bun'},
  {cat:'burger',sub:'经典款',sub_en:'Classic',flag:'🌍',name:'鱼排堡',en:'Fish Burger',p:['sea'],ing:'炸白身鱼排、塔塔酱、芝士片、生菜、汉堡胚',ing_en:'Fried white fish fillet, tartar sauce, cheese slice, lettuce, bun'},
  {cat:'burger',sub:'经典款',sub_en:'Classic',flag:'🌱',name:'素食堡',en:'Veggie Burger',p:['tofu'],ing:'黑豆或植物肉饼、生菜、番茄、洋葱圈、芝士、汉堡胚',ing_en:'Black bean or plant-based patty, lettuce, tomato, onion rings, cheese, bun'},
  {cat:'burger',sub:'异国特色',sub_en:'International',flag:'🇯🇵',name:'照烧猪肉堡',en:'Teriyaki Pork Burger',p:['pork'],ing:'猪肉片、照烧汁、生菜、芝士、蛋黄酱、汉堡胚',ing_en:'Pork slices, teriyaki sauce, lettuce, cheese, mayo, bun'},
  {cat:'burger',sub:'异国特色',sub_en:'International',flag:'🇯🇵',name:'日式米汉堡',en:'Rice Burger',p:['beef','sea'],ing:'压实米饭饼（代替面包）、烤肉或虾、生菜、照烧或海鲜酱',ing_en:'Pressed rice patties (instead of bun), grilled meat or shrimp, lettuce, teriyaki or seafood sauce'},
  {cat:'burger',sub:'异国特色',sub_en:'International',flag:'🇹🇷',name:'土耳其湿汉堡',en:'Islak Burger',p:['beef'],ing:'超薄牛肉饼、蒜、黑胡椒、浸番茄蒜酱的软面包',ing_en:'Ultra-thin beef patty, garlic, black pepper, soft bun soaked in tomato-garlic sauce'},
  {cat:'burger',sub:'异国特色',sub_en:'International',flag:'🇦🇺',name:'澳式甜菜根汉堡',en:'Aussie Burger',p:['beef','egg'],ing:'牛肉饼、甜菜根、菠萝片、煎蛋、培根、生菜、番茄',ing_en:'Beef patty, beetroot, pineapple slice, fried egg, bacon, lettuce, tomato'},
  {cat:'burger',sub:'异国特色',sub_en:'International',flag:'🇲🇾',name:'马来蛋包汉堡',en:'Ramly Burger',p:['beef','chicken','egg'],ing:'牛肉或鸡肉饼裹蛋皮、卷心菜丝、蛋黄酱、黄瓜、伍斯特酱、辣酱',ing_en:'Beef or chicken patty wrapped in egg, shredded cabbage, mayo, cucumber, Worcestershire sauce, chili sauce'},
  {cat:'burger',sub:'异国特色',sub_en:'International',flag:'🇮🇳',name:'印度炸土豆堡',en:'Vada Pav',p:['tofu'],ing:'炸土豆饼、面包、蒜辣酱、青辣酱、绿辣椒',ing_en:'Fried potato patty, bread, garlic chili chutney, green chutney, green chili'},

  {cat:'sandwich',sub:'冷三明治',sub_en:'Cold sandwiches',flag:'🇺🇸',name:'俱乐部三明治',en:'Club Sandwich',p:['chicken','egg'],ing:'三层吐司、火鸡或鸡肉、培根、生菜、番茄、煎蛋、蛋黄酱',ing_en:'Triple-stacked toast, turkey or chicken, bacon, lettuce, tomato, fried egg, mayo'},
  {cat:'sandwich',sub:'冷三明治',sub_en:'Cold sandwiches',flag:'🇺🇸',name:'培根生菜番茄三明治',en:'BLT',p:['pork'],ing:'培根、生菜、番茄、蛋黄酱、烤吐司',ing_en:'Bacon, lettuce, tomato, mayo, toasted bread'},
  {cat:'sandwich',sub:'冷三明治',sub_en:'Cold sandwiches',flag:'🇯🇵',name:'鸡蛋三明治',en:'Tamago Sando',p:['egg'],ing:'鸡蛋沙拉、蛋黄酱、白吐司、盐、糖',ing_en:'Egg salad, mayo, white bread, salt, sugar'},
  {cat:'sandwich',sub:'冷三明治',sub_en:'Cold sandwiches',flag:'🌍',name:'金枪鱼三明治',en:'Tuna Sando',p:['sea'],ing:'金枪鱼、蛋黄酱、洋葱碎、玉米粒、吐司',ing_en:'Tuna, mayo, chopped onion, corn, bread'},
  {cat:'sandwich',sub:'热压三明治',sub_en:'Pressed & grilled',flag:'🇮🇹',name:'意式帕尼尼',en:'Panini',p:['pork'],ing:'恰巴塔面包、火腿或萨拉米、马苏里拉、番茄、罗勒（压烤）',ing_en:'Ciabatta, ham or salami, mozzarella, tomato, basil (pressed & grilled)'},
  {cat:'sandwich',sub:'热压三明治',sub_en:'Pressed & grilled',flag:'🇨🇺',name:'古巴三明治',en:'Cuban Sandwich',p:['pork'],ing:'烤猪肉、火腿、瑞士芝士、酸黄瓜、黄芥末、古巴面包（压烤）',ing_en:'Roast pork, ham, Swiss cheese, pickles, yellow mustard, Cuban bread (pressed & grilled)'},
  {cat:'sandwich',sub:'热压三明治',sub_en:'Pressed & grilled',flag:'🇫🇷',name:'法式火腿芝士热三明治',en:'Croque Monsieur',p:['pork','egg'],ing:'火腿、格鲁耶尔芝士、白酱、烤吐司（加煎蛋即 Madame）',ing_en:'Ham, Gruyère cheese, béchamel, toasted bread (add a fried egg for Madame)'},
  {cat:'sandwich',sub:'热压三明治',sub_en:'Pressed & grilled',flag:'🇯🇵',name:'炸猪排三明治',en:'Katsu Sando',p:['pork'],ing:'炸猪排、卷心菜丝、猪排酱、黄芥末、白吐司',ing_en:'Fried pork cutlet, shredded cabbage, tonkatsu sauce, yellow mustard, white bread'},
  {cat:'sandwich',sub:'长面包·潜艇',sub_en:'Subs & hoagies',flag:'🇺🇸',name:'潜艇堡',en:'Sub / Hoagie',p:['pork','chicken'],ing:'长面包、冷切肉、芝士、生菜、番茄、洋葱、油醋汁',ing_en:'Long roll, cold cuts, cheese, lettuce, tomato, onion, oil & vinegar'},
  {cat:'sandwich',sub:'长面包·潜艇',sub_en:'Subs & hoagies',flag:'🇺🇸',name:'费城芝士牛肉',en:'Philly Cheesesteak',p:['beef'],ing:'薄牛肉片、洋葱、融化芝士、长面包',ing_en:'Thin beef slices, onion, melted cheese, long roll'},
  {cat:'sandwich',sub:'长面包·潜艇',sub_en:'Subs & hoagies',flag:'🇻🇳',name:'越南法包',en:'Bánh Mì',p:['pork'],ing:'法棍、烤猪肉、腌萝卜胡萝卜、黄瓜、香菜、辣椒、蛋黄酱',ing_en:'Baguette, roast pork, pickled daikon & carrot, cucumber, cilantro, chili, mayo'},
  {cat:'sandwich',sub:'长面包·潜艇',sub_en:'Subs & hoagies',flag:'🇲🇽',name:'墨西哥托塔',en:'Torta',p:['pork','chicken'],ing:'telera 软面包、烤肉、牛油果、豆泥、辣椒、芝士、番茄',ing_en:'Telera roll, grilled meat, avocado, refried beans, chili, cheese, tomato'},

  {cat:'wrap',sub:'美洲卷',sub_en:'American wraps',flag:'🇲🇽',name:'墨西哥卷饼',en:'Burrito',p:['beef','chicken','tofu'],ing:'面粉薄饼、米饭、豆子、肉、芝士、莎莎、酸奶油、牛油果',ing_en:'Flour tortilla, rice, beans, meat, cheese, salsa, sour cream, avocado'},
  {cat:'wrap',sub:'美洲卷',sub_en:'American wraps',flag:'🇲🇽',name:'塔可',en:'Taco',p:['beef','pork'],ing:'玉米饼、烤肉、洋葱、香菜、莎莎、青柠',ing_en:'Corn tortilla, grilled meat, onion, cilantro, salsa, lime'},
  {cat:'wrap',sub:'美洲卷',sub_en:'American wraps',flag:'🇺🇸',name:'鸡肉卷',en:'Chicken Wrap',p:['chicken'],ing:'薄饼、香煎鸡肉、生菜、番茄、芝士、酸奶酱',ing_en:'Tortilla, pan-fried chicken, lettuce, tomato, cheese, yogurt sauce'},
  {cat:'wrap',sub:'中东·旋转烤肉卷',sub_en:'Middle Eastern (rotisserie)',flag:'🇱🇧',name:'黎巴嫩沙威玛',en:'Shawarma',p:['chicken','beef'],ing:'转烤腌肉、皮塔或 lavash、蒜酱、腌菜、芝麻酱',ing_en:'Spit-roasted marinated meat, pita or lavash, garlic sauce, pickles, tahini'},
  {cat:'wrap',sub:'中东·旋转烤肉卷',sub_en:'Middle Eastern (rotisserie)',flag:'🇬🇷',name:'希腊旋转烤肉卷',en:'Gyros',p:['pork','chicken'],ing:'转烤猪或鸡肉、皮塔、酸奶黄瓜酱、薯条、番茄、洋葱',ing_en:'Spit-roasted pork or chicken, pita, tzatziki, fries, tomato, onion'},
  {cat:'wrap',sub:'中东·旋转烤肉卷',sub_en:'Middle Eastern (rotisserie)',flag:'🇹🇷',name:'土耳其旋转烤肉',en:'Döner Kebab',p:['beef'],ing:'转烤腌肉、lavash 或 pita、洋葱、番茄、酸奶酱',ing_en:'Spit-roasted marinated meat, lavash or pita, onion, tomato, yogurt sauce'},
  {cat:'wrap',sub:'中东·旋转烤肉卷',sub_en:'Middle Eastern (rotisserie)',flag:'🌍',name:'中东鹰嘴豆丸卷',en:'Falafel Wrap',p:['tofu'],ing:'炸鹰嘴豆丸、皮塔、生菜、番茄、酸黄瓜、芝麻酱',ing_en:'Fried falafel, pita, lettuce, tomato, pickles, tahini'},
  {cat:'wrap',sub:'亚洲卷',sub_en:'Asian rolls',flag:'🇨🇳',name:'手抓饼卷',en:'Scallion Pancake Wrap',p:['egg','pork'],ing:'手抓饼、煎蛋、炒肉、生菜、甜面酱',ing_en:'Flaky scallion pancake, fried egg, stir-fried meat, lettuce, sweet bean sauce'},
  {cat:'wrap',sub:'亚洲卷',sub_en:'Asian rolls',flag:'🇮🇳',name:'印度卡蒂卷',en:'Kathi Roll',p:['chicken','egg'],ing:'帕拉塔饼、烤腌肉、洋葱、青柠、酸辣酱',ing_en:'Paratha, grilled marinated meat, onion, lime, chutney'},
  {cat:'wrap',sub:'亚洲卷',sub_en:'Asian rolls',flag:'🇻🇳',name:'越南夏卷',en:'Summer Roll',p:['pork','sea'],ing:'米纸、虾或猪肉、米粉、生菜、薄荷、香菜、花生蘸酱（不炸）',ing_en:'Rice paper, shrimp or pork, rice noodles, lettuce, mint, cilantro, peanut dipping sauce (not fried)'},
  {cat:'wrap',sub:'亚洲卷',sub_en:'Asian rolls',flag:'🇵🇭',name:'菲律宾春卷',en:'Lumpia',p:['pork','sea'],ing:'薄春卷皮、猪肉或虾、胡萝卜、卷心菜、豆芽（炸）',ing_en:'Thin spring roll wrappers, pork or shrimp, carrot, cabbage, bean sprouts (fried)'},

  {cat:'rice',sub:'炒饭',sub_en:'Fried rice',flag:'🇨🇳',name:'扬州炒饭',en:'Yangzhou Fried Rice',p:['egg','sea'],ing:'米饭、鸡蛋、虾仁、叉烧、青豆、胡萝卜、葱',ing_en:'Rice, egg, shrimp, char siu, green peas, carrot, scallion'},
  {cat:'rice',sub:'炒饭',sub_en:'Fried rice',flag:'🇮🇩',name:'印尼炒饭',en:'Nasi Goreng',p:['chicken','egg'],ing:'米饭、甜酱油、虾酱、葱蒜辣椒、煎蛋、虾片',ing_en:'Rice, sweet soy sauce, shrimp paste, scallion-garlic-chili, fried egg, shrimp crackers'},
  {cat:'rice',sub:'炒饭',sub_en:'Fried rice',flag:'🇹🇭',name:'泰式菠萝炒饭',en:'Pineapple Fried Rice',p:['sea','egg'],ing:'米饭、虾、菠萝、腰果、咖喱粉、葱、鸡蛋',ing_en:'Rice, shrimp, pineapple, cashews, curry powder, scallion, egg'},
  {cat:'rice',sub:'炒饭',sub_en:'Fried rice',flag:'🇰🇷',name:'韩式泡菜炒饭',en:'Kimchi Fried Rice',p:['pork','egg'],ing:'米饭、泡菜、猪肉、麻油、煎蛋、海苔',ing_en:'Rice, kimchi, pork, sesame oil, fried egg, nori'},
  {cat:'rice',sub:'盖饭·丼',sub_en:'Rice bowls (donburi)',flag:'🇯🇵',name:'日式牛肉饭',en:'Gyudon',p:['beef'],ing:'肥牛片、洋葱、酱油味醂糖、米饭、温泉蛋',ing_en:'Fatty beef slices, onion, soy sauce-mirin-sugar, rice, onsen egg'},
  {cat:'rice',sub:'盖饭·丼',sub_en:'Rice bowls (donburi)',flag:'🇯🇵',name:'照烧鸡腿饭',en:'Teriyaki Chicken Don',p:['chicken'],ing:'鸡腿、照烧汁、米饭、白芝麻、葱',ing_en:'Chicken thigh, teriyaki sauce, rice, white sesame, scallion'},
  {cat:'rice',sub:'盖饭·丼',sub_en:'Rice bowls (donburi)',flag:'🇯🇵',name:'亲子丼',en:'Oyakodon',p:['chicken','egg'],ing:'鸡肉、鸡蛋、洋葱、高汤酱汁、米饭、葱',ing_en:'Chicken, egg, onion, dashi sauce, rice, scallion'},
  {cat:'rice',sub:'盖饭·丼',sub_en:'Rice bowls (donburi)',flag:'🇯🇵',name:'天妇罗盖饭',en:'Tendon',p:['sea'],ing:'米饭、炸虾天妇罗、蔬菜天妇罗、天丼酱汁',ing_en:'Rice, shrimp tempura, vegetable tempura, tendon sauce'},
  {cat:'rice',sub:'盖饭·丼',sub_en:'Rice bowls (donburi)',flag:'🇯🇵',name:'日式咖喱饭',en:'Curry Rice',p:['chicken','beef','pork'],ing:'肉、土豆、胡萝卜、洋葱、咖喱块、米饭',ing_en:'Meat, potato, carrot, onion, curry roux, rice'},
  {cat:'rice',sub:'盖饭·丼',sub_en:'Rice bowls (donburi)',flag:'🇹🇼',name:'台式卤肉饭',en:'Lu Rou Fan',p:['pork','egg'],ing:'卤肉丁、红葱酥、酱油、冰糖、五香粉、米饭、卤蛋',ing_en:'Braised diced pork, fried shallots, soy sauce, rock sugar, five-spice, rice, braised egg'},
  {cat:'rice',sub:'盖饭·丼',sub_en:'Rice bowls (donburi)',flag:'🇺🇸',name:'夏威夷生鱼饭',en:'Poke Bowl',p:['sea'],ing:'米饭、生三文鱼或金枪鱼、酱油、牛油果、海藻、洋葱、芝麻',ing_en:'Rice, raw salmon or tuna, soy sauce, avocado, seaweed, onion, sesame'},
  {cat:'rice',sub:'拌饭',sub_en:'Mixed rice',flag:'🇰🇷',name:'韩式石锅拌饭',en:'Bibimbap',p:['beef','egg'],ing:'米饭、牛肉末、菠菜、豆芽、胡萝卜、煎蛋、辣椒酱、麻油',ing_en:'Rice, ground beef, spinach, bean sprouts, carrot, fried egg, chili sauce, sesame oil'},
  {cat:'rice',sub:'拌饭',sub_en:'Mixed rice',flag:'🇯🇵',name:'鸡蛋拌饭',en:'Tamago Kake Gohan',p:['egg'],ing:'热米饭、生鸡蛋、酱油、葱',ing_en:'Hot rice, raw egg, soy sauce, scallion'},
  {cat:'rice',sub:'煲仔·焖饭',sub_en:'Claypot & braised rice',flag:'🇨🇳',name:'广式煲仔饭',en:'Claypot Rice',p:['pork','chicken'],ing:'米饭、腊肠、腊肉或鸡、青菜、酱油、葱（瓦煲焦底）',ing_en:'Rice, Chinese sausage, cured pork or chicken, greens, soy sauce, scallion (crispy claypot bottom)'},
  {cat:'rice',sub:'煲仔·焖饭',sub_en:'Claypot & braised rice',flag:'🇸🇬',name:'海南鸡饭',en:'Hainanese Chicken Rice',p:['chicken'],ing:'鸡腿、姜葱、鸡油香米饭、蒜姜蓉酱、黄瓜',ing_en:'Chicken thigh, ginger & scallion, chicken-fat rice, garlic-ginger sauce, cucumber'},
  {cat:'rice',sub:'手抓饭·香饭',sub_en:'Pilaf & spiced rice',flag:'🇮🇳',name:'印度比尔亚尼',en:'Biryani',p:['chicken','beef'],ing:'巴斯马蒂香米、腌肉、藏红花、洋葱酥、豆蔻丁香、酸奶',ing_en:'Basmati rice, marinated meat, saffron, fried onions, cardamom & cloves, yogurt'},
  {cat:'rice',sub:'手抓饭·香饭',sub_en:'Pilaf & spiced rice',flag:'🇲🇾',name:'马来椰浆饭',en:'Nasi Lemak',p:['sea','egg'],ing:'椰浆饭、江鱼仔、花生、黄瓜、参巴辣酱、水煮蛋',ing_en:'Coconut rice, dried anchovies, peanuts, cucumber, sambal chili, boiled egg'},
  {cat:'rice',sub:'饭团·饭卷',sub_en:'Rice balls & rolls',flag:'🇯🇵',name:'日式饭团',en:'Onigiri',p:['sea','egg'],ing:'米饭、三文鱼或梅子或肉松、海苔、盐',ing_en:'Rice, salmon or pickled plum or pork floss, nori, salt'},
  {cat:'rice',sub:'饭团·饭卷',sub_en:'Rice balls & rolls',flag:'🇰🇷',name:'韩式紫菜包饭',en:'Kimbap',p:['beef','egg'],ing:'海苔、米饭、牛肉或火腿、黄瓜、胡萝卜、腌萝卜、蛋皮、麻油',ing_en:'Nori, rice, beef or ham, cucumber, carrot, pickled radish, egg sheet, sesame oil'},
  {cat:'rice',sub:'饭团·饭卷',sub_en:'Rice balls & rolls',flag:'🇯🇵',name:'寿司卷',en:'Sushi Maki',p:['sea'],ing:'醋饭、海苔、三文鱼或金枪鱼或黄瓜、牛油果',ing_en:'Vinegared rice, nori, salmon or tuna or cucumber, avocado'},
  {cat:'rice',sub:'饭团·饭卷',sub_en:'Rice balls & rolls',flag:'🇹🇼',name:'台式饭团',en:'Fan Tuan',p:['pork'],ing:'糯米饭、肉松、卤肉、萝卜干、油条',ing_en:'Glutinous rice, pork floss, braised pork, dried radish, fried dough stick'},
  {cat:'rice',sub:'饭团·饭卷',sub_en:'Rice balls & rolls',flag:'🇮🇹',name:'意式炸饭团',en:'Arancini',p:['beef'],ing:'米饭、马苏里拉、肉酱、面包糠（炸）',ing_en:'Rice, mozzarella, meat sauce, breadcrumbs (fried)'},

  {cat:'noodle',sub:'汤面',sub_en:'Noodle soups',flag:'🇯🇵',name:'日式拉面',en:'Ramen',p:['pork','egg'],ing:'拉面、豚骨或酱油汤、叉烧、溏心蛋、海苔、葱',ing_en:'Ramen noodles, tonkotsu or shoyu broth, char siu, soft-boiled egg, nori, scallion'},
  {cat:'noodle',sub:'汤面',sub_en:'Noodle soups',flag:'🇻🇳',name:'越南牛肉粉',en:'Phở',p:['beef'],ing:'河粉、牛骨汤、生熟牛肉、八角桂皮、豆芽、香菜、青柠',ing_en:'Pho rice noodles, beef bone broth, raw & cooked beef, star anise & cinnamon, bean sprouts, cilantro, lime'},
  {cat:'noodle',sub:'汤面',sub_en:'Noodle soups',flag:'🇹🇭',name:'泰北咖喱面',en:'Khao Soi',p:['chicken'],ing:'蛋面、椰浆红咖喱汤、鸡肉、酸菜、红葱、青柠',ing_en:'Egg noodles, coconut red curry broth, chicken, pickled mustard greens, shallots, lime'},
  {cat:'noodle',sub:'汤面',sub_en:'Noodle soups',flag:'🇨🇳',name:'兰州牛肉拉面',en:'Lanzhou Beef Noodles',p:['beef'],ing:'手拉面、清牛肉汤、牛肉片、白萝卜、辣椒油、香菜',ing_en:'Hand-pulled noodles, clear beef broth, beef slices, daikon, chili oil, cilantro'},
  {cat:'noodle',sub:'汤面',sub_en:'Noodle soups',flag:'🇲🇾',name:'马来叻沙',en:'Laksa',p:['sea','chicken'],ing:'米粉、椰浆或酸辣汤、虾、鱼饼、豆芽、叻沙叶',ing_en:'Rice noodles, coconut or hot-and-sour broth, shrimp, fish cake, bean sprouts, laksa leaf'},
  {cat:'noodle',sub:'拌面·炒面',sub_en:'Tossed & fried noodles',flag:'🇹🇭',name:'泰式炒河粉',en:'Pad Thai',p:['sea','egg'],ing:'河粉、虾、豆腐、鸡蛋、豆芽、罗望子鱼露汁、花生碎',ing_en:'Rice noodles, shrimp, tofu, egg, bean sprouts, tamarind-fish sauce, crushed peanuts'},
  {cat:'noodle',sub:'拌面·炒面',sub_en:'Tossed & fried noodles',flag:'🇨🇳',name:'中式炒面',en:'Chow Mein / Lo Mein',p:['chicken','pork'],ing:'蛋面、肉丝、卷心菜、胡萝卜、蚝油、酱油',ing_en:'Egg noodles, shredded meat, cabbage, carrot, oyster sauce, soy sauce'},
  {cat:'noodle',sub:'拌面·炒面',sub_en:'Tossed & fried noodles',flag:'🇰🇷',name:'韩式杂菜',en:'Japchae',p:['beef','egg'],ing:'红薯粉丝、牛肉、菠菜、胡萝卜、香菇、麻油、酱油',ing_en:'Sweet potato glass noodles, beef, spinach, carrot, shiitake, sesame oil, soy sauce'},
  {cat:'noodle',sub:'拌面·炒面',sub_en:'Tossed & fried noodles',flag:'🇨🇳',name:'担担面',en:'Dan Dan Noodles',p:['pork'],ing:'面条、芝麻酱、辣椒油、肉末、花生、葱',ing_en:'Noodles, sesame paste, chili oil, ground pork, peanuts, scallion'},
  {cat:'noodle',sub:'拌面·炒面',sub_en:'Tossed & fried noodles',flag:'🇸🇬',name:'新加坡炒粿条',en:'Char Kway Teow',p:['sea','egg'],ing:'宽河粉、虾、腊肠、豆芽、鸡蛋、酱油',ing_en:'Wide rice noodles, shrimp, Chinese sausage, bean sprouts, egg, soy sauce'},

  {cat:'congee',sub:'粥',sub_en:'Congee',flag:'🇨🇳',name:'皮蛋瘦肉粥',en:'Century Egg Congee',p:['pork','egg'],ing:'大米、皮蛋、瘦肉、姜丝、葱、白胡椒',ing_en:'Rice, century egg, lean pork, shredded ginger, scallion, white pepper'},
  {cat:'congee',sub:'粥',sub_en:'Congee',flag:'🇨🇳',name:'潮汕海鲜粥',en:'Seafood Congee',p:['sea'],ing:'米、虾、鱿鱼、蛤蜊、芹菜、葱、姜',ing_en:'Rice, shrimp, squid, clams, celery, scallion, ginger'},
  {cat:'congee',sub:'粥',sub_en:'Congee',flag:'🇹🇭',name:'泰式鸡肉粥',en:'Jok',p:['chicken'],ing:'米、鸡肉、姜、鱼露、葱、油条',ing_en:'Rice, chicken, ginger, fish sauce, scallion, fried dough stick'},
  {cat:'congee',sub:'汤饭·泡饭',sub_en:'Soup rice',flag:'🇯🇵',name:'日式茶泡饭',en:'Ochazuke',p:['sea'],ing:'米饭、绿茶或高汤、鲑鱼或梅子、海苔、芥末',ing_en:'Rice, green tea or dashi, salmon or pickled plum, nori, wasabi'},
  {cat:'congee',sub:'汤饭·泡饭',sub_en:'Soup rice',flag:'🇰🇷',name:'韩式牛肉汤饭',en:'Gukbap',p:['beef'],ing:'米饭、牛肉、萝卜、葱、蒜、牛骨汤',ing_en:'Rice, beef, radish, scallion, garlic, beef bone broth'},
  {cat:'congee',sub:'汤饭·泡饭',sub_en:'Soup rice',flag:'🇰🇷',name:'泡菜豆腐汤配饭',en:'Kimchi Jjigae + Rice',p:['pork','tofu'],ing:'泡菜、豆腐、猪肉、辣椒粉、葱、米饭',ing_en:'Kimchi, tofu, pork, chili powder, scallion, rice'},

  {cat:'bundump',sub:'蒸包·夹饼',sub_en:'Buns & bao',flag:'🇹🇼',name:'台式刈包',en:'Gua Bao',p:['pork'],ing:'蒸饼、卤肉、酸菜、花生粉、香菜',ing_en:'Steamed bun, braised pork, pickled mustard greens, peanut powder, cilantro'},
  {cat:'bundump',sub:'蒸包·夹饼',sub_en:'Buns & bao',flag:'🇨🇳',name:'肉夹馍',en:'Rou Jia Mo',p:['pork'],ing:'白吉馍、卤肉碎、青椒、香菜',ing_en:'Baijimo flatbread, chopped braised pork, green pepper, cilantro'},
  {cat:'bundump',sub:'蒸包·夹饼',sub_en:'Buns & bao',flag:'🇨🇳',name:'叉烧包',en:'Char Siu Bao',p:['pork'],ing:'发面、叉烧肉、蚝油酱汁、糖',ing_en:'Leavened dough, char siu pork, oyster sauce, sugar'},
  {cat:'bundump',sub:'蒸包·夹饼',sub_en:'Buns & bao',flag:'🇻🇪',name:'委内瑞拉玉米饼',en:'Arepa',p:['chicken','tofu'],ing:'玉米饼对半、鸡肉丝或黑豆、芝士、牛油果',ing_en:'Halved corn cake, shredded chicken or black beans, cheese, avocado'},
  {cat:'bundump',sub:'蒸包·夹饼',sub_en:'Buns & bao',flag:'🌎',name:'拉美肉馅饼',en:'Empanada',p:['beef','chicken'],ing:'面皮、碎肉、洋葱、水煮蛋、橄榄、孜然（烤或炸）',ing_en:'Dough, ground meat, onion, boiled egg, olives, cumin (baked or fried)'},
  {cat:'bundump',sub:'饺子',sub_en:'Dumplings',flag:'🇨🇳',name:'中式饺子',en:'Jiaozi',p:['pork'],ing:'饺子皮、猪肉、白菜、韭菜、姜、葱（煮/蒸/煎）',ing_en:'Dumpling wrappers, pork, napa cabbage, chives, ginger, scallion (boiled/steamed/pan-fried)'},
  {cat:'bundump',sub:'饺子',sub_en:'Dumplings',flag:'🇨🇳',name:'上海小笼包',en:'Xiaolongbao',p:['pork'],ing:'薄面皮、猪肉、皮冻（汤汁）、姜、醋蘸料',ing_en:'Thin dough, pork, aspic (soup), ginger, vinegar dipping sauce'},
  {cat:'bundump',sub:'饺子',sub_en:'Dumplings',flag:'🇯🇵',name:'日式煎饺',en:'Gyoza',p:['pork'],ing:'饺子皮、猪肉、卷心菜、韭菜、蒜姜（煎+蒸）',ing_en:'Dumpling wrappers, pork, cabbage, chives, garlic & ginger (pan-fried & steamed)'},
  {cat:'bundump',sub:'饺子',sub_en:'Dumplings',flag:'🇰🇷',name:'韩式饺子',en:'Mandu',p:['pork','tofu'],ing:'饺子皮、猪肉、豆腐、泡菜、粉丝、葱',ing_en:'Dumpling wrappers, pork, tofu, kimchi, glass noodles, scallion'},
  {cat:'bundump',sub:'饺子',sub_en:'Dumplings',flag:'🇨🇳',name:'馄饨',en:'Wonton',p:['pork','sea'],ing:'薄馄饨皮、猪肉或虾、葱、高汤',ing_en:'Thin wonton wrappers, pork or shrimp, scallion, broth'},
  {cat:'bundump',sub:'饺子',sub_en:'Dumplings',flag:'🇳🇵',name:'尼泊尔蒸饺',en:'Momo',p:['chicken'],ing:'面皮、鸡肉或蔬菜、洋葱、姜蒜、番茄蘸酱',ing_en:'Dough, chicken or vegetables, onion, ginger & garlic, tomato dipping sauce'},
  {cat:'bundump',sub:'蒸炸点心',sub_en:'Dim sum (steamed & fried)',flag:'🇨🇳',name:'虾饺',en:'Har Gow',p:['sea'],ing:'澄面皮、虾仁、竹笋、猪油',ing_en:'Wheat starch wrapper, shrimp, bamboo shoots, lard'},
  {cat:'bundump',sub:'蒸炸点心',sub_en:'Dim sum (steamed & fried)',flag:'🇨🇳',name:'烧卖',en:'Siu Mai',p:['pork','sea'],ing:'黄色薄皮、猪肉、虾、香菇',ing_en:'Thin yellow wrapper, pork, shrimp, shiitake'},
  {cat:'bundump',sub:'蒸炸点心',sub_en:'Dim sum (steamed & fried)',flag:'🇨🇳',name:'春卷',en:'Spring Roll',p:['pork','sea'],ing:'春卷皮、肉丝或虾、卷心菜、胡萝卜、豆芽（炸）',ing_en:'Spring roll wrappers, shredded meat or shrimp, cabbage, carrot, bean sprouts (fried)'},

  {cat:'snack',sub:'烧烤串',sub_en:'Skewers & grills',flag:'🇯🇵',name:'日式烤鸡串',en:'Yakitori',p:['chicken'],ing:'鸡肉块、葱、照烧汁或盐、竹签',ing_en:'Chicken pieces, scallion, teriyaki sauce or salt, bamboo skewers'},
  {cat:'snack',sub:'烧烤串',sub_en:'Skewers & grills',flag:'🌏',name:'东南亚沙嗲',en:'Satay',p:['chicken','beef'],ing:'腌肉串、姜黄香茅、花生蘸酱、黄瓜洋葱',ing_en:'Marinated meat skewers, turmeric & lemongrass, peanut dipping sauce, cucumber & onion'},
  {cat:'snack',sub:'烧烤串',sub_en:'Skewers & grills',flag:'🌍',name:'中东烤肉串',en:'Shish Kebab',p:['beef'],ing:'腌牛肉块、洋葱、彩椒、孜然、竹签',ing_en:'Marinated beef cubes, onion, bell pepper, cumin, bamboo skewers'},
  {cat:'snack',sub:'烧烤串',sub_en:'Skewers & grills',flag:'🇯🇵',name:'日式烤鱿鱼',en:'Ikayaki',p:['sea'],ing:'鱿鱼、酱油糖照烧汁、竹签',ing_en:'Squid, soy-sugar teriyaki sauce, bamboo skewers'},
  {cat:'snack',sub:'油炸·煎烙小吃',sub_en:'Fried & griddled snacks',flag:'🇯🇵',name:'大阪章鱼烧',en:'Takoyaki',p:['sea','egg'],ing:'面糊、章鱼丁、红姜、葱、章鱼烧酱、蛋黄酱、木鱼花',ing_en:'Batter, diced octopus, pickled red ginger, scallion, takoyaki sauce, mayo, bonito flakes'},
  {cat:'snack',sub:'油炸·煎烙小吃',sub_en:'Fried & griddled snacks',flag:'🇯🇵',name:'大阪烧',en:'Okonomiyaki',p:['pork','egg'],ing:'卷心菜、面糊、鸡蛋、猪肉片、大阪烧酱、蛋黄酱、木鱼花',ing_en:'Cabbage, batter, egg, pork slices, okonomiyaki sauce, mayo, bonito flakes'},
  {cat:'snack',sub:'油炸·煎烙小吃',sub_en:'Fried & griddled snacks',flag:'🇯🇵',name:'日式可乐饼',en:'Korokke',p:['tofu'],ing:'土豆泥、洋葱、面包糠（可加肉末，炸）',ing_en:'Mashed potato, onion, breadcrumbs (optional ground meat, fried)'},
  {cat:'snack',sub:'油炸·煎烙小吃',sub_en:'Fried & griddled snacks',flag:'🇨🇳',name:'葱油饼',en:'Scallion Pancake',p:['tofu'],ing:'面团、葱、盐、油（煎）',ing_en:'Dough, scallion, salt, oil (pan-fried)'},

  {cat:'dessert',sub:'米食甜点',sub_en:'Rice desserts',flag:'🇹🇭',name:'泰式芒果糯米饭',en:'Mango Sticky Rice',p:['tofu'],ing:'糯米、椰浆、糖、盐、芒果',ing_en:'Glutinous rice, coconut milk, sugar, salt, mango'},
  {cat:'dessert',sub:'米食甜点',sub_en:'Rice desserts',flag:'🇨🇳',name:'汤圆',en:'Tang Yuan',p:['tofu'],ing:'糯米粉、黑芝麻或花生馅、糖、姜糖水',ing_en:'Glutinous rice flour, black sesame or peanut filling, sugar, ginger syrup'},
  {cat:'dessert',sub:'米食甜点',sub_en:'Rice desserts',flag:'🇯🇵',name:'日式麻糬',en:'Mochi',p:['tofu'],ing:'糯米粉、红豆沙或草莓或冰淇淋',ing_en:'Glutinous rice flour, red bean paste or strawberry or ice cream'},
  {cat:'dessert',sub:'冰品',sub_en:'Frozen treats',flag:'🇰🇷',name:'韩式刨冰',en:'Bingsu',p:['tofu'],ing:'刨冰、炼乳、红豆、水果、年糕',ing_en:'Shaved ice, condensed milk, red bean, fruit, rice cake'},
  {cat:'dessert',sub:'冰品',sub_en:'Frozen treats',flag:'🇵🇭',name:'菲律宾刨冰',en:'Halo-Halo',p:['egg'],ing:'刨冰、炼乳、豆、果冻、布丁、紫薯冰淇淋',ing_en:'Shaved ice, condensed milk, beans, jelly, pudding, purple yam ice cream'},
  {cat:'dessert',sub:'冰品',sub_en:'Frozen treats',flag:'🇻🇳',name:'越南甜汤',en:'Chè',p:['tofu'],ing:'绿豆或红豆、椰浆、西米、果冻',ing_en:'Mung bean or red bean, coconut milk, tapioca pearls, jelly'},
  {cat:'dessert',sub:'糕饼',sub_en:'Cakes & pastries',flag:'🇰🇷',name:'韩式糖饼',en:'Hotteok',p:['tofu'],ing:'面团、红糖、坚果、肉桂（煎）',ing_en:'Dough, brown sugar, nuts, cinnamon (pan-fried)'},
  {cat:'dessert',sub:'糕饼',sub_en:'Cakes & pastries',flag:'🇯🇵',name:'鲷鱼烧',en:'Taiyaki',p:['egg'],ing:'面糊、红豆沙或卡仕达（鱼形模具）',ing_en:'Batter, red bean paste or custard (fish-shaped mold)'},
  {cat:'dessert',sub:'糕饼',sub_en:'Cakes & pastries',flag:'🇨🇳',name:'蛋挞',en:'Egg Tart',p:['egg'],ing:'酥皮、鸡蛋、牛奶、糖',ing_en:'Puff pastry, egg, milk, sugar'},
  {cat:'dessert',sub:'糕饼',sub_en:'Cakes & pastries',flag:'🇯🇵',name:'铜锣烧',en:'Dorayaki',p:['egg'],ing:'松饼皮、红豆沙',ing_en:'Pancake layers, red bean paste'},
];

const formats = {
  custom:{em:'⭐',name:'我的菜谱',name_en:'My Recipes',desc:'你用 AI 一句话生成、云端同步的菜。',desc_en:'Recipes you generate with AI, synced to the cloud.'},
  burger:{em:'🍔',name:'汉堡',name_en:'Burgers',desc:'肉饼夹圆面包，全球都有本地版本。',desc_en:'A patty in a round bun — every cuisine has its own.'},
  sandwich:{em:'🥪',name:'三明治',name_en:'Sandwiches',desc:'面包夹料，分冷食、热压、长面包潜艇。',desc_en:'Filled bread — cold, pressed, or long subs.'},
  wrap:{em:'🌯',name:'卷类',name_en:'Wraps',desc:'薄饼或皮塔卷馅，包法多样。',desc_en:'Flatbread or pita wraps, many styles.'},
  rice:{em:'🍚',name:'饭类',name_en:'Rice',desc:'主食里的核心：炒、盖、拌、煲、抓、团。',desc_en:'A staple at the center of the meal: fried, bowls, mixed, claypot, pilaf, balls.'},
  noodle:{em:'🍜',name:'面·粉',name_en:'Noodles',desc:'汤的、拌的、炒的，米麦皆有。',desc_en:'In soup, tossed, or fried — wheat and rice.'},
  congee:{em:'🥘',name:'粥·汤饭',name_en:'Congee & Soup Rice',desc:'熬煮或汤泡的米食，暖胃好消化。',desc_en:'Simmered or soup-soaked rice — warm and easy on the stomach.'},
  bundump:{em:'🥟',name:'包·饺·点心',name_en:'Buns, Dumplings & Dim Sum',desc:'面皮包馅：蒸包夹饼、饺子、蒸炸点心。',desc_en:'Filled dough: steamed buns, dumplings, dim sum.'},
  snack:{em:'🍢',name:'串·小吃',name_en:'Skewers & Snacks',desc:'街边手持：烤串、油炸、铁板煎烙。',desc_en:'Street eats: skewers, deep-fried, griddled.'},
  dessert:{em:'🍰',name:'甜品',name_en:'Desserts',desc:'米食、冰品、糕饼等甜点。',desc_en:'Rice desserts, frozen treats, and pastries.'},
};
const formatOrder=['custom','burger','sandwich','wrap','rice','noodle','congee','bundump','snack','dessert'];
const pInfo={
  pork:{zh:'🐷猪',en:'🐷Pork'}, chicken:{zh:'🐔鸡',en:'🐔Chicken'},
  beef:{zh:'🐄牛',en:'🐄Beef'}, sea:{zh:'🐟鱼虾',en:'🐟Seafood'},
  egg:{zh:'🥚蛋',en:'🥚Egg'}, tofu:{zh:'🫛豆腐素',en:'🫛Tofu/Veg'}
};
const PSET=['pork','chicken','beef','sea','egg','tofu'];

/* 界面文案字典：{key:{zh,en}}。{n} 为占位符，由 trf() 替换。 */
const UI = {
  pageTitle:{zh:'全球快餐大全 · 云同步', en:'World Fast Food · Cloud Sync'},
  loginH2:{zh:'登录 / 注册', en:'Sign in / Sign up'},
  loginIntro:{zh:'用邮箱登录，收藏和菜谱会云端同步到所有设备', en:'Sign in with email; favorites and recipes sync to all your devices'},
  phEmail:{zh:'邮箱', en:'Email'},
  phPw:{zh:'密码（至少 6 位）', en:'Password (min 6 chars)'},
  signIn:{zh:'登录', en:'Sign in'},
  signUp:{zh:'注册新账号', en:'Create account'},
  or:{zh:'或', en:'or'},
  google:{zh:'用 Google 登录', en:'Sign in with Google'},
  loginNote:{zh:'数据云端同步，多设备共享', en:'Cloud sync across your devices'},
  kicker:{zh:'汉堡·三明治·卷·饭·面·粥·点心·小吃·甜品', en:'Burgers · Sandwiches · Wraps · Rice · Noodles · Congee · Dim Sum · Snacks · Desserts'},
  h1:{zh:'全球<span class="accent">快餐</span>大全', en:'World <span class="accent">Fast Food</span>'},
  subtitle:{zh:'9 大类 × 子类细分 · 蛋白质筛选 · 收藏 · AI 加菜 · 云同步', en:'9 categories × subtypes · protein filter · favorites · AI recipes · cloud sync'},
  logout:{zh:'退出', en:'Sign out'},
  dice:{zh:'🎲 今天吃啥？随机选一道', en:'🎲 What to eat? Pick one'},
  aiOpen:{zh:'✨ 一句话加菜谱', en:'✨ Add a recipe in one line'},
  filtLabel:{zh:'按蛋白质筛选 · 或看收藏', en:'Filter by protein · or view favorites'},
  fAll:{zh:'全部', en:'All'},
  fFav:{zh:'♥ 我的收藏', en:'♥ Favorites'},
  fPork:{zh:'🐷 猪', en:'🐷 Pork'},
  fChicken:{zh:'🐔 鸡', en:'🐔 Chicken'},
  fBeef:{zh:'🐄 牛', en:'🐄 Beef'},
  fSea:{zh:'🐟 鱼虾', en:'🐟 Seafood'},
  fEgg:{zh:'🥚 蛋', en:'🥚 Egg'},
  fTofu:{zh:'🫛 豆腐素', en:'🫛 Tofu/Veg'},
  fMix:{zh:'🍲 混合', en:'🍲 Mixed'},
  footer:{zh:'9 大类 · 几十个国家 · ♥ 收藏 · ✨ AI 加菜 · ☁️ 跨设备同步', en:'9 categories · dozens of countries · ♥ favorites · ✨ AI recipes · ☁️ cross-device sync'},
  cartTitle:{zh:'🛒 买菜备忘录', en:'🛒 Shopping list'},
  phCart:{zh:'加一样要买的东西…', en:'Add something to buy…'},
  cartClear:{zh:'清除已买', en:'Clear done'},
  aiTitle:{zh:'✨ 一句话加菜谱', en:'✨ Add a recipe in one line'},
  phAi:{zh:'一句话描述，例：韩式甜辣炸鸡', en:'Describe a dish, e.g. Korean sweet-spicy fried chicken'},
  aiStatusDefault:{zh:'输入一道菜的描述，AI 会自动生成材料和蛋白质标签，加入「⭐ 我的菜谱」并云端同步。', en:'Describe a dish; AI generates ingredients and protein tags, adds it to ⭐ My Recipes and syncs.'},
  aiNote:{zh:'注：AI 加菜已通过 Supabase 后端代理支持线上使用（需登录）。生成的菜谱会加入「⭐ 我的菜谱」并云端同步。', en:'Note: AI add-recipe works online via a Supabase proxy (login required). New recipes go to ⭐ My Recipes and sync.'},
  // 动态文案（app.js 用）
  syncing:{zh:'☁️ 同步中…', en:'☁️ Syncing…'},
  syncFail:{zh:'⚠️ 同步失败：', en:'⚠️ Sync failed: '},
  synced:{zh:'✓ 已云端同步', en:'✓ Synced'},
  needEmailPw:{zh:'请输入邮箱和密码', en:'Enter email and password'},
  signingIn:{zh:'登录中…', en:'Signing in…'},
  signInFail:{zh:'登录失败：', en:'Sign-in failed: '},
  needPw6:{zh:'请输入邮箱，密码至少 6 位', en:'Enter email; password ≥ 6 chars'},
  signingUp:{zh:'注册中…', en:'Signing up…'},
  signUpFail:{zh:'注册失败：', en:'Sign-up failed: '},
  signUpOk:{zh:'注册成功！如开启了邮箱确认，请先去邮箱点确认链接，再回来登录。', en:'Signed up! If email confirmation is on, confirm via the email link, then sign in.'},
  googleRedirect:{zh:'跳转到 Google…', en:'Redirecting to Google…'},
  googleFail:{zh:'Google 登录失败：', en:'Google sign-in failed: '},
  favEmpty:{zh:'还没有收藏～ 点菜品上的 ♡ 收藏，就会出现在这里。', en:'No favorites yet — tap ♡ on a dish and it shows up here.'},
  favHave:{zh:'你收藏了 <b>{n}</b> 道', en:'You have <b>{n}</b> favorites'},
  favToCart:{zh:'🛒 把全部收藏的材料加入买菜清单', en:'🛒 Add all favorite ingredients to list'},
  favAllAdded:{zh:'✓ 已全部加入清单', en:'✓ All added to list'},
  catCount:{zh:'{n} 种', en:'{n} kinds'},
  emptyList:{zh:'这个蛋白质下暂时没有菜，换一个试试 🍳', en:'No dishes for this protein — try another 🍳'},
  diceResult:{zh:'→ 今天就做「{n}」吧！', en:'→ Let\'s make "{n}" today!'},
  ingLabel:{zh:'材料', en:'Ingredients'},
  favOn:{zh:'♥ 已收藏', en:'♥ Saved'},
  favOff:{zh:'♡ 收藏', en:'♡ Save'},
  addCart:{zh:'🛒 加入买菜清单', en:'🛒 Add to list'},
  added:{zh:'✓ 已加入', en:'✓ Added'},
  del:{zh:'✕ 删除', en:'✕ Delete'},
  mix:{zh:'🍲混合', en:'🍲Mixed'},
  cartEmpty:{zh:'清单空空的～<br>手动添加，或在菜里点「加入买菜清单」', en:'Your list is empty —<br>add manually, or tap "Add to list" on a dish'},
  cartLeft:{zh:'还要买 {n} 样', en:'{n} left to buy'},
  aiGenerating:{zh:'正在生成「{n}」…', en:'Generating "{n}"…'},
  aiExpired:{zh:'登录已过期，请重新登录', en:'Session expired, please sign in again'},
  aiFail:{zh:'AI 生成失败，请换个描述再试', en:'Generation failed, try another description'},
  aiAdded:{zh:'已加入「⭐ 我的菜谱」：{n}', en:'Added to ⭐ My Recipes: {n}'},
  aiNetErr:{zh:'网络错误，请稍后再试', en:'Network error, try again later'},
  cartAria:{zh:'买菜清单', en:'Shopping list'},
  settingsAria:{zh:'设置', en:'Settings'},
  settingsTitle:{zh:'⚙️ 设置', en:'⚙️ Settings'},
  setAccount:{zh:'账号', en:'Account'},
  setLang:{zh:'语言', en:'Language'},
  setShare:{zh:'菜谱分享', en:'Share recipes'},
  aiExport:{zh:'导出我的菜谱', en:'Export my recipes'},
  aiCopy:{zh:'复制', en:'Copy'},
  aiDoImport:{zh:'确认导入', en:'Import'},
  phCode:{zh:'菜谱码会显示在这里 / 把别人的码粘贴到这里', en:'Code appears here / paste a shared code here'},
  aiCopied:{zh:'✓ 已复制到剪贴板', en:'✓ Copied to clipboard'},
  aiExportEmpty:{zh:'你还没有 AI 生成的菜谱', en:'You have no AI recipes yet'},
  aiImportBad:{zh:'菜谱码无效，请检查后重试', en:'Invalid code, please check and retry'},
  aiImportEmpty:{zh:'没有可导入的新菜谱', en:'No new recipes to import'},
  aiImportDone:{zh:'✓ 导入了 {n} 道菜', en:'✓ Imported {n} recipes'},
};
